name: ourshop_ecommerce
description: "A new Flutter project."

version: 1.0.0+3

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  bloc: ^9.0.0
  cached_network_image: 3.4.1
  carousel_slider: 5.0.0
  cupertino_icons: ^1.0.8
  dart_jsonwebtoken: ^2.14.2
  dio: ^5.7.0
  equatable: ^2.0.7
  flick_video_player: 0.9.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.0.0
  flutter_dotenv: ^5.2.1
  flutter_form_builder: ^9.5.0  
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: 4.0.1
  flutter_stripe: ^11.3.0
  flutter_svg: ^2.0.17
  form_builder_validators: 11.0.0
  get_it: ^8.0.3
  go_router: ^14.6.3
  image_picker: 1.1.2
  infinite_scroll_pagination: ^4.1.0
  intl: any
  shared_preferences: ^2.3.5
  toastification: ^2.3.0
  url_launcher: ^6.3.1
  video_player: ^2.9.2
  wakelock_plus: ^1.2.10
  webview_flutter: ^4.10.0
  web_socket_channel: ^3.0.1
  rxdart: ^0.28.0
  stomp_dart_client: ^2.1.0
  
  http: 
  google_sign_in: ^6.2.2 
  fluttertoast: ^8.2.8
  provider: ^6.1.2
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  font_awesome_flutter: ^10.8.0
  sign_in_with_apple: ^6.1.4
  crypto: 3.0.6
  dropdown_search: ^6.0.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/icons/
    - assets/logos/
    - .env.dev
    - .env.prod
    
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
