// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbOKP2M2tE4j5yjnly4gAfXG_iGWTLKY',
    appId: '1:544549440537:web:edfade2af3448b7443ee88',
    messagingSenderId: '544549440537',
    projectId: 'ourshop-fea4a',
    authDomain: 'ourshop-fea4a.firebaseapp.com',
    storageBucket: 'ourshop-fea4a.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRIC2zDjrHoKZkKK2x1ehaDij8Va0Lrig',
    appId: '1:544549440537:android:d5c4f6c74e932e5a43ee88',
    messagingSenderId: '544549440537',
    projectId: 'ourshop-fea4a',
    storageBucket: 'ourshop-fea4a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxH5KNAD0EuhZ4dghC01WjDWPgmve1Imc',
    appId: '1:544549440537:ios:15eff35560f49e7243ee88',
    messagingSenderId: '544549440537',
    projectId: 'ourshop-fea4a',
    storageBucket: 'ourshop-fea4a.firebasestorage.app',
    iosClientId: '544549440537-aloalfq5lm2ij33pk3kroq89c36biam4.apps.googleusercontent.com',
    iosBundleId: 'szfibersystem.ourshopEcommerce.ec',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxH5KNAD0EuhZ4dghC01WjDWPgmve1Imc',
    appId: '1:544549440537:ios:e9d9891db4bf383a43ee88',
    messagingSenderId: '544549440537',
    projectId: 'ourshop-fea4a',
    storageBucket: 'ourshop-fea4a.firebasestorage.app',
    iosClientId: '544549440537-gv9vl8c01fmoo2jv2in8kmqno6nqf8mh.apps.googleusercontent.com',
    iosBundleId: 'szfibersystem.ourshop.com',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDbmHPASSN1Ixd6uQtLfer32jkGLJQyLLE',
    appId: '1:544549440537:web:d4cbd7c1d68a290f43ee88',
    messagingSenderId: '544549440537',
    projectId: 'ourshop-fea4a',
    authDomain: 'ourshop-fea4a.firebaseapp.com',
    storageBucket: 'ourshop-fea4a.firebasestorage.app',
  );
}
